name: Docker Image CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file ./.devcontainer/Dockerfile --tag shift2sdv:$(date +%s) --target dev

    - name: Run tests in Docker container
      run: |
        # Get the tag from the build step dynamically
        IMAGE_TAG="shift2sdv:$(date +%s)"
        
        # Run pytest inside the Docker container using the local image
        docker run --rm $IMAGE_TAG pytest
