name: Docker Image CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file ./.devcontainer/Dockerfile --tag shift2sdv:$(date +%s) --target dev

    - name: Run tests in Docker container
      run: |
        docker run --rm \
          --privileged \
          -v ${{ github.workspace }}:/workspaces/shift2sdv \
          -w /workspaces/shift2sdv \
          shift2sdv:${{ github.sha }} \
          pytest

